---
- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: prereq
      become: true
    - role: download
      become: true

- hosts: master
  roles:
    - role: k3s/master
      become: true

- hosts: node
  roles:
    - role: k3s/node
      become: true

- hosts: master
  roles:
    - role: k3s/post
      become: true
